package com.cloudtogo.plugins.proto.pojo.generator.config.model;

import com.thoughtworks.xstream.annotations.XStreamAlias;

/**
 * Created by cheney on 2017/10/26.
 */
@XStreamAlias("protoc")
public class Protoc {

    @XStreamAlias("class-name")
    private String className;
    private String pkg;

    /**
     * @return The default is the proto file name.
     */
    public String getClassName() {
        return className;
    }

    /**
     * If the class name generated by the probuf-plugin is not the proto file name,
     * you need config the special name.
     * @param className
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * @return The default is the package value defined in the proto file.
     */
    public String getPkg() {
        return pkg;
    }

    /**
     * If the package value does not equal that defined in the proto file,
     * you need config the special value.
     * @param pkg
     */
    public void setPkg(String pkg) {
        this.pkg = pkg;
    }
}
